- name: Create user for promtail
  ansible.builtin.user:
    name: "{{ promtail_user }}"
    shell: /usr/sbin/nologin

- name: Download promtail binary
  ansible.builtin.get_url:
    url: "{{ promtail_binary_url }}"
    dest: "/tmp/promtail.tar.gz"
    mode: '0644'

- name: Extract promtail binary
  ansible.builtin.unarchive:
    src: "/tmp/promtail.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Create systemd service file
  ansible.builtin.template:
    src: "promtail.service.j2"
    dest: "/etc/systemd/system/promtail.service"
    mode: '0644'

- name: Create config directory
  ansible.builtin.file:
    path: "/etc/promtail"
    state: directory
    mode: '0755'

- name: Create config file
  ansible.builtin.template:
    src: "promtail.config.j2"
    dest: "/etc/promtail/config.yaml"
    mode: '0644'

- name: Create log directory
  ansible.builtin.file:
    path: "/var/log/promtail"
    state: directory
    mode: '0755'

- name: Create log file
  ansible.builtin.file:
    path: "/var/log/promtail/promtail.log"
    state: touch
    mode: '0644'

- name: Enable and start promtail service
  ansible.builtin.systemd:
    name: "promtail"
    state: started
    enabled: yes
