all:
  children:
    base_setup_servers:
      hosts:
        server1: {}
        monitoring_server: {}

    docker_servers:
      hosts:
        server1: {}
        monitoring_server: {}

    node_exporter_servers:
      hosts:
        server1: {}

    promtail_servers:
      hosts:
        server1: {}

    prometheus_servers:
      hosts:
        monitoring_server: {}

    grafana_servers:
      hosts:
        monitoring_server: {}

    loki_servers:
      hosts:
        monitoring_server: {}

  vars:
    server1:
      ansible_host: 192.168.88.73
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    monitoring_server:
      ansible_host: 192.168.88.76
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
