all:
  children:
    grafana_servers:
      hosts:
        server1: {}
        
    prometheus_servers:
      hosts:
        server1: {}

    loki_servers:
      hosts:
        server1: {}
        
  vars:
    server1:
      ansible_host: 192.168.1.10
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
