- name: Set timezone
  timezone:
    name: "{{ timezone }}"
    state: present
- name: Install chrony for time synchronization
  apt:
    name: chrony
    state: present

- name: Enable and start chrony service
  service:
    name: chrony
    state: started
    enabled: yes
