- name: Install prerequisites for Docker
  apt: 
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: true
    state: present


